---

- name: Echo
  hosts: localhost
  gather_facts: false
  connection: local
  become: true
  become_user: paroscale

  tasks:
    - name: Print debug message
      debug: 
        msg: Hello, World!

    - name: Create a directory
      file:
        path: /home/paroscale/myapp
        state: directory
        mode: '0755'
        owner: paroscale
        group: paroscale

    - name: Copy a local file to the directory
      copy:
        content: "Hello, from Ansible!"
        dest: /home/paroscale/myapp/hello.txt
        mode: '0644'

...

