---

- name: Mathematical Operations in Ansible
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    a: 10
    b: 5

  tasks:
    - name: Addition
      debug:
        msg: "Sum: {{ a + b }}"

    - name: Subtraction
      debug:
        msg: "Difference: {{ a - b }}"

    - name: Multiplication
      debug:
        msg: "Product: {{ a * b }}"

    - name: Division
      debug:
        msg: "Quotient: {{ a / b }}"

    - name: Modulo
      debug:
        msg: "Remainder: {{ a % b }}"

    - name: Exponent
      debug:
        msg: "Power: {{ a ** b }}"

...
