---

- name: Run python script to read a file
  hosts: localhost
  gather_facts: false
  connection: local 

  tasks: 
    - name: Set file content using custom plugin
      set_fact:
        file_content: "{{ lookup('read_file', '/home/paroscale/myapp/hello.txt') }}"

    - name: Print file content
      debug: 
        msg: "{{ file_content }}" 

    # - name: Print file content 
    #   debug: 
    #     msg: "{{ file_output.stdout }}"
